(() => {
'use strict';
const DATA=window.MERIDIAN_DATA, M=DATA.meridians, $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
M.forEach(m=>m.points=m.points.map(p=>({code:p[0],name:p[1],category:p[2],position:p[3],location:p[4],indications:p[5],pairings:p[6],meridianCode:m.code,meridianName:m.name,classic:m.classic,color:m.color})));
const points=M.flatMap(m=>m.points), byCode=new Map(points.map(p=>[p.code,p]));
const state={mi:0,code:'LU7',progress:0,playing:true,speed:1,mode:'particles',tab:'overview',view:'meridian',filter:'all',favorites:new Set(),yaw:0,pitch:.05,distance:6.2,locked:false,fallback:false};
try{const s=JSON.parse(localStorage.getItem('meridian-atlas-v2')||'{}');Object.assign(state,s);state.favorites=new Set(s.favorites||[])}catch{}state.fallback=false
const save=()=>{try{localStorage.setItem('meridian-atlas-v2',JSON.stringify({...state,favorites:[...state.favorites]}))}catch{}};
const active=()=>M[state.mi], selected=()=>byCode.get(state.code)||active().points[0];
function sidebar(q=''){
 const list=$('#meridianList');list.innerHTML='';q=q.trim().toLowerCase();
 if(state.view==='animation'){
  [['particles','粒子流动','连续粒子沿经络循行'],['trace','逐段寻迹','按循行顺序逐段点亮'],['pulse','脉冲高光','脉冲式强调当前路径']].forEach(([k,n,d])=>{const b=document.createElement('button');b.className='meridian-item '+(state.mode===k?'active':'');b.innerHTML=`<span class="meridian-code">${k==='particles'?'粒':k==='trace'?'迹':'脉'}</span><div><strong>${n}</strong><small>${d}</small></div><span class="meridian-arrow">›</span>`;b.onclick=()=>{state.mode=k;render();save()};list.append(b)});return;
 }
 const source=state.view==='point'||state.view==='favorite'?points:M;
 source.filter(x=>state.view!=='favorite'||state.favorites.has(x.code)).filter(x=>{
  if(x.points&&state.filter!=='all'&&x.type!==state.filter)return false;
  return !q||`${x.code}${x.name}${x.english||''}${x.meridianName||''}`.toLowerCase().includes(q);
 }).forEach(x=>{const isM=!!x.points,b=document.createElement('button');b.className='meridian-item '+((isM?M[state.mi].code:x.code)===(isM?x.code:state.code)?'active':'');b.innerHTML=`<span class="meridian-code">${x.code}</span><div><strong>${x.name}</strong><small>${isM?x.english+' · '+x.points.length+' 穴位':x.meridianName+' · '+x.category}</small></div><span class="meridian-arrow">${!isM&&state.favorites.has(x.code)?'★':'›'}</span>`;b.onclick=()=>isM?selectMeridian(M.indexOf(x),true):selectPoint(x.code);list.append(b)});
 if(!list.children.length)list.innerHTML='<div class="source-card"><div class="source-icon">空</div><div><strong>暂无内容</strong><p>调整筛选或搜索关键词。</p></div></div>';
}
function detail(){
 const p=selected();$('#pointCode').textContent=p.code;$('#pointName').textContent=p.name;$('#pointMeridian').textContent=`${p.meridianName} · ${p.category}`;$('#favoritePoint').textContent=state.favorites.has(p.code)?'★':'☆';$('#favoritePoint').classList.toggle('active',state.favorites.has(p.code));
 const c=$('#detailContent');
 if(state.tab==='overview')c.innerHTML=`<section class="detail-section"><h3>标准定位摘要</h3><div class="detail-card"><p>${p.location}</p></div></section><section class="detail-section"><h3>传统应用索引</h3><div class="tag-row">${p.indications.map(x=>`<span class="tag">${x}</span>`).join('')}</div></section><section class="detail-section"><h3>数据标注</h3><div class="detail-card"><p>名称与定位摘要参考 ${DATA.sources.national} 及 ${DATA.sources.who}。3D点位为教学映射，不用于针刺定位。</p></div></section>`;
 else if(state.tab==='classic')c.innerHTML=`<section class="detail-section"><h3>经脉古籍节录</h3><div class="detail-card"><p class="classic-quote">“${p.classic}”</p><span class="classic-source">${DATA.sources.classic}（节录）</span></div></section><section class="detail-section"><h3>阅读边界</h3><div class="detail-card"><p>古籍文字反映传统医学理论与历史语境，不应直接等同于现代解剖结构或临床证据。</p></div></section>`;
 else c.innerHTML=`<section class="detail-section"><h3>常见教学配伍</h3><div class="detail-card">${p.pairings.map(([n,d])=>`<div class="pairing-item"><span class="pairing-code">${n.split(' ')[0]}</span><div><strong>${n}</strong><p>${d}</p></div></div>`).join('')}</div></section><section class="detail-section"><h3>使用边界</h3><div class="detail-card"><p>配伍仅作为知识索引；实际临床需结合辨证、禁忌、个体情况和专业操作规范。</p></div></section>`;
}
function render(){
 const m=active();$('#currentCode').textContent=m.code;$('#currentMeridianName').textContent=m.name;$('#pointCount').textContent=m.points.length;$('#progressRange').value=Math.round(state.progress*1000);$('#progressLabel').textContent=Math.round(state.progress*100)+'%';$('#playPause').textContent=state.playing?'Ⅱ':'▶';$('#speedSelect').value=String(state.speed);$('#favoriteCount').textContent=state.favorites.size;$('#lockView').classList.toggle('active',state.locked);$$('#modeSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));sidebar($('#searchInput').value);detail();if(state.fallback)drawFallback();
}
function selectMeridian(i,play=false){state.mi=(i+M.length)%M.length;state.code=active().points[Math.min(2,active().points.length-1)].code;state.progress=0;if(play)state.playing=true;render();save()}
function selectPoint(code){const p=byCode.get(code);if(!p)return;state.code=code;state.mi=M.findIndex(m=>m.code===p.meridianCode);render();save()}

// WebGL renderer
const canvas=$('#glCanvas'),stage=$('#stage');let gl,prog,buf,vp=new Float32Array(16),last=performance.now(),fps=[];
const V=`attribute vec3 p;attribute vec4 c;uniform mat4 m;uniform float s;varying vec4 v;void main(){gl_Position=m*vec4(p,1.);gl_PointSize=s;v=c;}`;
const F=`precision mediump float;varying vec4 v;uniform float q;void main(){if(q>.5&&length(gl_PointCoord-.5)>.5)discard;gl_FragColor=v;}`;
const mat={mul:(a,b)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o},persp:(f,a,n,fa)=>{const t=1/Math.tan(f/2),o=new Float32Array(16);o[0]=t/a;o[5]=t;o[10]=(fa+n)/(n-fa);o[11]=-1;o[14]=2*fa*n/(n-fa);return o},look:(e,t,u)=>{let z=norm(sub(e,t)),x=norm(cross(u,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1])}};
const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>{const l=Math.hypot(...a)||1;return a.map(x=>x/l)};
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
function initGL(){if(location.search.includes('fallback=1'))throw Error('forced fallback');gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('WebGL unavailable');prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,V));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,F));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(prog));buf=gl.createBuffer();gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);requestAnimationFrame(frame)}
function camera(){const r=stage.getBoundingClientRect(),cp=Math.cos(state.pitch),e=[Math.sin(state.yaw)*cp*state.distance,.25+Math.sin(state.pitch)*state.distance,Math.cos(state.yaw)*cp*state.distance];vp=mat.mul(mat.persp(Math.PI/4,Math.max(.3,r.width/Math.max(1,r.height)),.1,50),mat.look(e,[0,.25,0],[0,1,0]))}
function upload(verts,mode,size=1){const data=new Float32Array(verts.flat());gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);const p=gl.getAttribLocation(prog,'p'),c=gl.getAttribLocation(prog,'c');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,3,gl.FLOAT,false,28,0);gl.enableVertexAttribArray(c);gl.vertexAttribPointer(c,4,gl.FLOAT,false,28,12);gl.uniformMatrix4fv(gl.getUniformLocation(prog,'m'),false,vp);gl.uniform1f(gl.getUniformLocation(prog,'s'),size);gl.uniform1f(gl.getUniformLocation(prog,'q'),mode===gl.POINTS?1:0);gl.drawArrays(mode,0,verts.length)}
const v=(p,c,a=1)=>[p[0],p[1],p[2],c[0],c[1],c[2],a];
function body(){const c=[.28,.38,.33],lines=[[[0,2.45,0],[0,1.55,0]],[[0,1.55,0],[-.65,1.25,0]],[[-.65,1.25,0],[-1.65,0,0]],[[0,1.55,0],[.65,1.25,0]],[[.65,1.25,0],[1.65,0,0]],[[0,1.55,0],[0,-.35,0]],[[0,-.35,0],[-.4,-2.2,0]],[[0,-.35,0],[.4,-2.2,0]]];upload(lines.flatMap(x=>x.map(p=>v(p,c,.42))),gl.LINES,1);const head=[];for(let i=0;i<32;i++){let a=i/31*Math.PI*2;head.push(v([Math.cos(a)*.29,2.25+Math.sin(a)*.35,0],c,.35))}upload(head,gl.LINE_STRIP,1)}
function path(m,activePath){const lim=state.mode==='trace'&&activePath?Math.max(2,Math.floor(m.path.length*state.progress)+1):m.path.length,c=activePath?m.color:m.color.map(x=>x*.32),a=activePath?.92:.28;upload(m.path.slice(0,lim).map(p=>v(p,c,a)),gl.LINE_STRIP,1)}
function sample(path,t){let lens=[],total=0;for(let i=1;i<path.length;i++){let l=Math.hypot(path[i][0]-path[i-1][0],path[i][1]-path[i-1][1],path[i][2]-path[i-1][2]);lens.push(l);total+=l}let d=t*total;for(let i=0;i<lens.length;i++){if(d<=lens[i]){let q=d/lens[i],a=path[i],b=path[i+1];return a.map((x,j)=>x+(b[j]-x)*q)}d-=lens[i]}return path.at(-1)}
function scene(now){body();M.forEach((m,i)=>path(m,i===state.mi));const m=active();upload(points.map(p=>v(p.position,p.meridianCode===m.code?p.color:[.38,.43,.40],p.meridianCode===m.code?1:.35)),gl.POINTS,10);let count=state.mode==='pulse'?18:38,arr=[],pulse=(Math.sin(now*.006)+1)/2;for(let i=0;i<count;i++){let t=(state.progress-i/count*(state.mode==='particles'?.5:.18)+1)%1,pp=sample(m.path,t);arr.push(v(pp,m.color,state.mode==='pulse'?.45+pulse*.5:.9))}upload(arr,gl.POINTS,state.mode==='pulse'?14+pulse*8:12)}
function resize(){const r=stage.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,innerWidth<900?1.2:1.5),w=Math.max(1,Math.floor(r.width*d)),h=Math.max(1,Math.floor(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}
function frame(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(state.playing){state.progress=(state.progress+dt*.095*state.speed)%1;$('#progressRange').value=Math.round(state.progress*1000);$('#progressLabel').textContent=Math.round(state.progress*100)+'%'}resize();camera();gl.clearColor(.018,.042,.034,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(prog);scene(now);fps.push(1/Math.max(dt,.001));if(fps.length>24)fps.shift();if(fps.length===24)$('#fpsValue').textContent=Math.min(99,Math.round(fps.reduce((a,b)=>a+b)/fps.length));requestAnimationFrame(frame)}
function project(p){let x=p[0],y=p[1],z=p[2],w=vp[3]*x+vp[7]*y+vp[11]*z+vp[15];return[(vp[0]*x+vp[4]*y+vp[8]*z+vp[12])/w,(vp[1]*x+vp[5]*y+vp[9]*z+vp[13])/w]}
function hit(cx,cy){const r=stage.getBoundingClientRect();let best=null,d0=28;points.forEach(p=>{let s=project(p.position),x=(s[0]*.5+.5)*r.width,y=(1-(s[1]*.5+.5))*r.height,d=Math.hypot(cx-r.left-x,cy-r.top-y);if(d<d0){d0=d;best=p}});return best}
function tip(p,x,y){const t=$('#hoverTooltip');if(!p){t.hidden=true;return}t.hidden=false;t.innerHTML=`<strong>${p.code} · ${p.name}</strong><span>${p.meridianName} · ${p.category}</span>`;const r=stage.getBoundingClientRect();t.style.left=Math.min(r.width-190,x-r.left)+'px';t.style.top=Math.min(r.height-90,y-r.top)+'px'}
let ptr=new Map(),start=null,pinch=null,moved=false;canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);ptr.set(e.pointerId,[e.clientX,e.clientY]);start=[e.clientX,e.clientY,performance.now()];moved=false;if(ptr.size===2){let a=[...ptr.values()];pinch=[Math.hypot(a[1][0]-a[0][0],a[1][1]-a[0][1]),Math.atan2(a[1][1]-a[0][1],a[1][0]-a[0][0])]}};canvas.onpointermove=e=>{let old=ptr.get(e.pointerId);if(!old)return;ptr.set(e.pointerId,[e.clientX,e.clientY]);if(state.locked)return;if(ptr.size===1){let dx=e.clientX-old[0],dy=e.clientY-old[1];if(Math.hypot(dx,dy)>1)moved=true;state.yaw-=dx*.008;state.pitch=Math.max(-.75,Math.min(.75,state.pitch-dy*.006))}else if(ptr.size===2){let a=[...ptr.values()],d=Math.hypot(a[1][0]-a[0][0],a[1][1]-a[0][1]),ang=Math.atan2(a[1][1]-a[0][1],a[1][0]-a[0][0]);if(pinch){state.distance=Math.max(3.4,Math.min(10,state.distance*pinch[0]/d));state.yaw+=ang-pinch[1]}pinch=[d,ang]}if(ptr.size===1&&!moved)tip(hit(e.clientX,e.clientY),e.clientX,e.clientY);else tip(null)};canvas.onpointerup=e=>{let s=start;ptr.delete(e.pointerId);pinch=null;if(s){let dx=e.clientX-s[0],dy=e.clientY-s[1],dur=performance.now()-s[2];if(Math.abs(dx)>85&&Math.abs(dy)<55&&dur<700)selectMeridian(state.mi+(dx<0?1:-1),true);else if(!moved&&Math.hypot(dx,dy)<12){let p=hit(e.clientX,e.clientY);if(p)selectPoint(p.code)}}tip(null);start=null};canvas.onpointercancel=e=>{ptr.delete(e.pointerId);pinch=null};canvas.onwheel=e=>{if(state.locked)return;e.preventDefault();state.distance=Math.max(3.4,Math.min(10,state.distance*(1+Math.sign(e.deltaY)*.08))) };canvas.onmousemove=e=>{if(!ptr.size)tip(hit(e.clientX,e.clientY),e.clientX,e.clientY)};canvas.onmouseleave=()=>tip(null);
function drawFallback(){const svg=$('#fallbackSvg'),m=active(),map=([x,y])=>[300+x*150,450-y*160],d=m.path.map((p,i)=>`${i?'L':'M'}${map(p).join(' ')}`).join(' ');svg.innerHTML='<ellipse class="fallback-body" cx="300" cy="125" rx="65" ry="78"/><path class="fallback-body" d="M238 205 Q300 175 362 205 L390 430 Q300 470 210 430 Z"/><path class="fallback-body" d="M235 225 L105 480 M365 225 L495 480 M255 430 L230 815 M345 430 L370 815" fill="none" stroke-linecap="round" stroke-width="48"/>'+`<path class="fallback-path" d="${d}"/>`+m.points.map(p=>{let q=map(p.position);return`<circle class="fallback-point" cx="${q[0]}" cy="${q[1]}" r="9"><title>${p.code} ${p.name}</title></circle>`}).join('')}
function fallback(err){console.error('WebGL initialization failed:',err);state.fallback=true;canvas.hidden=true;$('#fallback2d').hidden=false;const head=$('#fallback2d .fallback-head');if(head)head.innerHTML='<strong>3D渲染初始化失败，已切换二维模式</strong><span>可打开浏览器控制台查看具体原因</span>';drawFallback()}

$('#playPause').onclick=()=>{state.playing=!state.playing;render();save()};$('#prevMeridian').onclick=()=>selectMeridian(state.mi-1,true);$('#nextMeridian').onclick=()=>selectMeridian(state.mi+1,true);$('#progressRange').oninput=e=>{state.progress=+e.target.value/1000;state.playing=false;render();save()};$('#speedSelect').onchange=e=>{state.speed=+e.target.value;save()};$('#zoomIn').onclick=()=>state.distance=Math.max(3.4,state.distance*.88);$('#zoomOut').onclick=()=>state.distance=Math.min(10,state.distance*1.12);$('#resetView').onclick=()=>{state.yaw=0;state.pitch=.05;state.distance=6.2};$('#lockView').onclick=()=>{state.locked=!state.locked;render()};$('#favoritePoint').onclick=()=>{state.favorites.has(state.code)?state.favorites.delete(state.code):state.favorites.add(state.code);render();save()};$('#favoriteToggle').onclick=()=>{state.view='favorite';$$('.nav-pill').forEach(x=>x.classList.remove('active'));$('#favoriteToggle').classList.add('active');sidebar($('#searchInput').value)};$('#searchInput').oninput=e=>sidebar(e.target.value);$('#collapseLeft').onclick=()=>{$('.left-panel').classList.toggle('collapsed');$('.workspace').classList.toggle('left-collapsed')};$$('.filter-chip').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$('.filter-chip').forEach(x=>x.classList.toggle('active',x===b));sidebar($('#searchInput').value)});$$('.detail-tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;$$('.detail-tab').forEach(x=>x.classList.toggle('active',x===b));detail()});$$('#modeSwitch button').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render();save()});$$('.nav-pill[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;$$('.nav-pill').forEach(x=>x.classList.toggle('active',x===b));sidebar($('#searchInput').value)});
render();try{initGL()}catch(e){fallback(e)}window.addEventListener('beforeunload',save);
})();
